// <auto-generated />
namespace GPS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Graph3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Graph3));
        
        string IMigrationMetadata.Id
        {
            get { return "201702262034395_Graph3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
